export type CountryOption = {
  code: string;
  name: string;
  flag: string;
  dial: string;
};

export function flagFromCountryCode(code: string): string {
  const upper = code.toUpperCase();
  if (upper.length !== 2 || !/^[A-Z]{2}$/.test(upper)) return "🌐";
  return String.fromCodePoint(
    ...upper.split("").map((char) => 127397 + char.charCodeAt(0)),
  );
}

function c(code: string, name: string, dial: string): CountryOption {
  return { code, name, flag: flagFromCountryCode(code), dial };
}

/** Países mais usados na comunidade — aparecem como atalhos no seletor de telefone */
export const popularCountryCodes = [
  "BR",
  "AR",
  "UY",
  "CL",
  "CO",
  "PE",
  "MX",
  "US",
  "PT",
  "ES",
  "FR",
  "DE",
  "GB",
  "IT",
  "RU",
  "PL",
  "TR",
  "JP",
  "KR",
  "CN",
] as const;

export const countries: CountryOption[] = [
  c("AF", "Afeganistão", "+93"),
  c("ZA", "África do Sul", "+27"),
  c("AL", "Albânia", "+355"),
  c("DE", "Alemanha", "+49"),
  c("AD", "Andorra", "+376"),
  c("AO", "Angola", "+244"),
  c("SA", "Arábia Saudita", "+966"),
  c("DZ", "Argélia", "+213"),
  c("AR", "Argentina", "+54"),
  c("AM", "Armênia", "+374"),
  c("AU", "Austrália", "+61"),
  c("AT", "Áustria", "+43"),
  c("AZ", "Azerbaijão", "+994"),
  c("BS", "Bahamas", "+1"),
  c("BD", "Bangladesh", "+880"),
  c("BB", "Barbados", "+1"),
  c("BH", "Bahrein", "+973"),
  c("BE", "Bélgica", "+32"),
  c("BZ", "Belize", "+501"),
  c("BJ", "Benin", "+229"),
  c("BY", "Bielorrússia", "+375"),
  c("BO", "Bolívia", "+591"),
  c("BA", "Bósnia e Herzegovina", "+387"),
  c("BW", "Botsuana", "+267"),
  c("BR", "Brasil", "+55"),
  c("BN", "Brunei", "+673"),
  c("BG", "Bulgária", "+359"),
  c("BF", "Burkina Faso", "+226"),
  c("BI", "Burundi", "+257"),
  c("BT", "Butão", "+975"),
  c("CV", "Cabo Verde", "+238"),
  c("CM", "Camarões", "+237"),
  c("KH", "Camboja", "+855"),
  c("CA", "Canadá", "+1"),
  c("QA", "Catar", "+974"),
  c("KZ", "Cazaquistão", "+7"),
  c("TD", "Chade", "+235"),
  c("CL", "Chile", "+56"),
  c("CN", "China", "+86"),
  c("CY", "Chipre", "+357"),
  c("CO", "Colômbia", "+57"),
  c("KM", "Comores", "+269"),
  c("CG", "Congo", "+242"),
  c("CD", "Congo (DRC)", "+243"),
  c("KP", "Coreia do Norte", "+850"),
  c("KR", "Coreia do Sul", "+82"),
  c("CI", "Costa do Marfim", "+225"),
  c("CR", "Costa Rica", "+506"),
  c("HR", "Croácia", "+385"),
  c("CU", "Cuba", "+53"),
  c("DK", "Dinamarca", "+45"),
  c("DJ", "Djibuti", "+253"),
  c("DM", "Dominica", "+1"),
  c("EG", "Egito", "+20"),
  c("SV", "El Salvador", "+503"),
  c("AE", "Emirados Árabes", "+971"),
  c("EC", "Equador", "+593"),
  c("ER", "Eritreia", "+291"),
  c("SK", "Eslováquia", "+421"),
  c("SI", "Eslovênia", "+386"),
  c("ES", "Espanha", "+34"),
  c("US", "Estados Unidos", "+1"),
  c("EE", "Estônia", "+372"),
  c("SZ", "Eswatini", "+268"),
  c("ET", "Etiópia", "+251"),
  c("FJ", "Fiji", "+679"),
  c("PH", "Filipinas", "+63"),
  c("FI", "Finlândia", "+358"),
  c("FR", "França", "+33"),
  c("GA", "Gabão", "+241"),
  c("GM", "Gâmbia", "+220"),
  c("GH", "Gana", "+233"),
  c("GE", "Geórgia", "+995"),
  c("GD", "Granada", "+1"),
  c("GR", "Grécia", "+30"),
  c("GT", "Guatemala", "+502"),
  c("GY", "Guiana", "+592"),
  c("GN", "Guiné", "+224"),
  c("GQ", "Guiné Equatorial", "+240"),
  c("GW", "Guiné-Bissau", "+245"),
  c("HT", "Haiti", "+509"),
  c("HN", "Honduras", "+504"),
  c("HU", "Hungria", "+36"),
  c("YE", "Iêmen", "+967"),
  c("IN", "Índia", "+91"),
  c("ID", "Indonésia", "+62"),
  c("IQ", "Iraque", "+964"),
  c("IR", "Irã", "+98"),
  c("IE", "Irlanda", "+353"),
  c("IS", "Islândia", "+354"),
  c("IL", "Israel", "+972"),
  c("IT", "Itália", "+39"),
  c("JM", "Jamaica", "+1"),
  c("JP", "Japão", "+81"),
  c("JO", "Jordânia", "+962"),
  c("KW", "Kuwait", "+965"),
  c("LA", "Laos", "+856"),
  c("LS", "Lesoto", "+266"),
  c("LV", "Letônia", "+371"),
  c("LB", "Líbano", "+961"),
  c("LR", "Libéria", "+231"),
  c("LY", "Líbia", "+218"),
  c("LI", "Liechtenstein", "+423"),
  c("LT", "Lítuânia", "+370"),
  c("LU", "Luxemburgo", "+352"),
  c("MK", "Macedônia do Norte", "+389"),
  c("MG", "Madagascar", "+261"),
  c("MY", "Malásia", "+60"),
  c("MW", "Malawi", "+265"),
  c("MV", "Maldivas", "+960"),
  c("ML", "Mali", "+223"),
  c("MT", "Malta", "+356"),
  c("MA", "Marrocos", "+212"),
  c("MU", "Maurício", "+230"),
  c("MR", "Mauritânia", "+222"),
  c("MX", "México", "+52"),
  c("MM", "Mianmar", "+95"),
  c("MZ", "Moçambique", "+258"),
  c("MD", "Moldávia", "+373"),
  c("MC", "Mônaco", "+377"),
  c("MN", "Mongólia", "+976"),
  c("ME", "Montenegro", "+382"),
  c("NA", "Namíbia", "+264"),
  c("NP", "Nepal", "+977"),
  c("NI", "Nicarágua", "+505"),
  c("NE", "Níger", "+227"),
  c("NG", "Nigéria", "+234"),
  c("NO", "Noruega", "+47"),
  c("NZ", "Nova Zelândia", "+64"),
  c("OM", "Omã", "+968"),
  c("NL", "Países Baixos", "+31"),
  c("PW", "Palau", "+680"),
  c("PA", "Panamá", "+507"),
  c("PG", "Papua-Nova Guiné", "+675"),
  c("PK", "Paquistão", "+92"),
  c("PY", "Paraguai", "+595"),
  c("PE", "Peru", "+51"),
  c("PL", "Polônia", "+48"),
  c("PT", "Portugal", "+351"),
  c("KE", "Quênia", "+254"),
  c("KG", "Quirguistão", "+996"),
  c("GB", "Reino Unido", "+44"),
  c("CF", "República Centro-Africana", "+236"),
  c("DO", "República Dominicana", "+1"),
  c("CZ", "República Tcheca", "+420"),
  c("RO", "Romênia", "+40"),
  c("RW", "Ruanda", "+250"),
  c("RU", "Rússia", "+7"),
  c("WS", "Samoa", "+685"),
  c("SM", "San Marino", "+378"),
  c("LC", "Santa Lúcia", "+1"),
  c("ST", "São Tomé e Príncipe", "+239"),
  c("SN", "Senegal", "+221"),
  c("SL", "Serra Leoa", "+232"),
  c("RS", "Sérvia", "+381"),
  c("SC", "Seychelles", "+248"),
  c("SG", "Singapura", "+65"),
  c("SY", "Síria", "+963"),
  c("SO", "Somália", "+252"),
  c("LK", "Sri Lanka", "+94"),
  c("SD", "Sudão", "+249"),
  c("SS", "Sudão do Sul", "+211"),
  c("SE", "Suécia", "+46"),
  c("CH", "Suíça", "+41"),
  c("SR", "Suriname", "+597"),
  c("TH", "Tailândia", "+66"),
  c("TW", "Taiwan", "+886"),
  c("TJ", "Tajiquistão", "+992"),
  c("TZ", "Tanzânia", "+255"),
  c("TL", "Timor-Leste", "+670"),
  c("TG", "Togo", "+228"),
  c("TO", "Tonga", "+676"),
  c("TT", "Trinidad e Tobago", "+1"),
  c("TN", "Tunísia", "+216"),
  c("TM", "Turcomenistão", "+993"),
  c("TR", "Turquia", "+90"),
  c("TV", "Tuvalu", "+688"),
  c("UA", "Ucrânia", "+380"),
  c("UG", "Uganda", "+256"),
  c("UY", "Uruguai", "+598"),
  c("UZ", "Uzbequistão", "+998"),
  c("VU", "Vanuatu", "+678"),
  c("VA", "Vaticano", "+39"),
  c("VE", "Venezuela", "+58"),
  c("VN", "Vietnã", "+84"),
  c("ZM", "Zâmbia", "+260"),
  c("ZW", "Zimbábue", "+263"),
];

export const countryCodes = countries.map((country) => country.code) as [
  string,
  ...string[],
];

export function getCountry(code: string): CountryOption | undefined {
  return countries.find((country) => country.code === code);
}

export function getCountryFlag(code: string): string {
  return getCountry(code)?.flag ?? flagFromCountryCode(code);
}

export function getCountryLabel(code: string): string {
  const country = getCountry(code);
  return country ? `${country.flag} ${country.name}` : code;
}
