import type { WarmupModeDef } from "@/lib/warmup/modes";

/** Defaults usados na seed automática quando o banco está vazio. */
export const FALLBACK_WARMUP_MODES: (WarmupModeDef & { defaultMaps: string[] })[] = [
  {
    id: "arena_1x1",
    slug: "arena_1x1",
    label: "Nova Arena 1x1",
    modeLabel: "Nova Arena 1x1",
    icon: "Boxes",
    accent: "from-violet-600 to-purple-800",
    defaultMaps: ["de_mirage", "de_dust2"],
  },
  {
    id: "deathmatch",
    slug: "deathmatch",
    label: "Deathmatch",
    modeLabel: "Deathmatch",
    icon: "Skull",
    accent: "from-rose-600 to-red-800",
    defaultMaps: ["de_dust2", "de_mirage", "de_inferno", "awp_lego"],
  },
  {
    id: "multimod",
    slug: "multimod",
    label: "Multimod",
    modeLabel: "Multimod",
    icon: "Gamepad2",
    accent: "from-indigo-600 to-blue-800",
    defaultMaps: ["de_mirage", "de_nuke"],
  },
  {
    id: "rifle",
    slug: "rifle",
    label: "Rifle",
    modeLabel: "Rifle",
    icon: "Crosshair",
    accent: "from-amber-600 to-orange-800",
    defaultMaps: ["de_dust2", "de_mirage"],
  },
  {
    id: "pistol",
    slug: "pistol",
    label: "Pistol",
    modeLabel: "Pistol",
    icon: "Target",
    accent: "from-cyan-600 to-teal-800",
    defaultMaps: ["de_inferno", "de_mirage"],
  },
  {
    id: "headshot",
    slug: "headshot",
    label: "Headshot",
    modeLabel: "Headshot",
    icon: "ScanFace",
    accent: "from-fuchsia-600 to-pink-800",
    defaultMaps: ["de_dust2"],
  },
  {
    id: "retake",
    slug: "retake",
    label: "Retake",
    modeLabel: "Retake",
    icon: "Bomb",
    accent: "from-emerald-600 to-green-800",
    defaultMaps: ["de_mirage", "de_inferno", "de_nuke"],
  },
  {
    id: "surf",
    slug: "surf",
    label: "Surf",
    modeLabel: "Surf",
    icon: "Waves",
    accent: "from-sky-600 to-blue-900",
    defaultMaps: ["surf_utopia"],
  },
  {
    id: "casual",
    slug: "casual",
    label: "Casual",
    modeLabel: "Casual",
    icon: "Users",
    accent: "from-slate-600 to-zinc-800",
    defaultMaps: ["de_office", "de_italy"],
  },
  {
    id: "kz",
    slug: "kz",
    label: "KZ",
    modeLabel: "KZ",
    icon: "Mountain",
    accent: "from-lime-600 to-emerald-900",
    defaultMaps: ["kz_map"],
  },
  {
    id: "warmup",
    slug: "warmup",
    label: "Warmup",
    modeLabel: "Warmup",
    icon: "Zap",
    accent: "from-amber-500 to-orange-600",
    defaultMaps: ["de_dust2", "de_mirage"],
  },
];
