/** CsgoSkinCatalog rows used by demo inventory + bridge (shared with seed). */
export const DEMO_CS2_CATALOG_SKINS = [
  {
    id: "knife_gamma_doppler",
    weaponId: "weapon_knife",
    weaponName: "Karambit",
    paintkit: 568,
    paintkitName: "Gamma Doppler",
    rarity: "rare",
    category: "knife",
  },
  {
    id: "ak47_inheritance",
    weaponId: "weapon_ak47",
    weaponName: "AK-47",
    paintkit: 1207,
    paintkitName: "Inheritance",
    rarity: "covert",
    category: "rifle",
  },
  {
    id: "m4a4_howl",
    weaponId: "weapon_m4a1",
    weaponName: "M4A4",
    paintkit: 309,
    paintkitName: "Howl",
    rarity: "rare",
    category: "rifle",
  },
  {
    id: "awp_dragon_lore",
    weaponId: "weapon_awp",
    weaponName: "AWP",
    paintkit: 344,
    paintkitName: "Dragon Lore",
    rarity: "rare",
    category: "sniper",
  },
  {
    id: "deagle_blaze",
    weaponId: "weapon_deagle",
    weaponName: "Desert Eagle",
    paintkit: 38,
    paintkitName: "Blaze",
    rarity: "classified",
    category: "pistol",
  },
  {
    id: "glock_fade",
    weaponId: "weapon_glock",
    weaponName: "Glock-18",
    paintkit: 38,
    paintkitName: "Fade",
    rarity: "classified",
    category: "pistol",
  },
  {
    id: "mp9_starlight",
    weaponId: "weapon_mp9",
    weaponName: "MP9",
    paintkit: 1090,
    paintkitName: "Starlight Protector",
    rarity: "covert",
    category: "smg",
  },
  {
    id: "knife_bf_fade",
    weaponId: "weapon_knife",
    weaponName: "Butterfly Knife",
    paintkit: 413,
    paintkitName: "Fade",
    rarity: "rare",
    category: "knife",
  },
  {
    id: "usp_kill_confirmed",
    weaponId: "weapon_usp_silencer",
    weaponName: "USP-S",
    paintkit: 315,
    paintkitName: "Kill Confirmed",
    rarity: "covert",
    category: "pistol",
  },
] as const;
